{
 "title": "EURe-rebalancing-bot",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "EURe and EUR prices",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "EURe_price_curve{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "EURe Curve"
    },
    {
     "expr": "EUR_price_feed{container=\"eure-rebalancing-bot\"}",
     "legendFormat": "EUR price feed"
    }
   ]
  },
  {
   "title": "Last updated",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_updated{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EURe Curve price",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "EURe_price_curve{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EUR price feed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "EUR_price_feed{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WXDAI to EURe drift",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "WXDAI_to_EURe_drift{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "Drift"
    },
    {
     "expr": "drift_threshold{container=\"eure-rebalancing-bot\"}",
     "legendFormat": "Threshold"
    }
   ]
  },
  {
   "title": "EURe to WXDAI drift",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "EURe_to_WXDAI_drift{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "Drift"
    },
    {
     "expr": "drift_threshold{container=\"eure-rebalancing-bot\"}",
     "legendFormat": "Threshold"
    }
   ]
  },
  {
   "title": "WXDAI to EURe drift",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WXDAI_to_EURe_drift{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "Drift"
    }
   ]
  },
  {
   "title": "EURe to WXDAI drift",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "EURe_to_WXDAI_drift{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "Drift"
    }
   ]
  },
  {
   "title": "Drift threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "drift_threshold{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WXDAI amount to swap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amount_WXDAI{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EURe amount to swap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "amount_EURe{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Safe's WXDAI balance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "safe_WXDAI_balance{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "WXDAI balance"
    }
   ]
  },
  {
   "title": "Safe's EURe balance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "safe_EURe_balance{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "EURe balance"
    }
   ]
  },
  {
   "title": "Safe's WXDAI balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "safe_WXDAI_balance{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "EURe balance"
    }
   ]
  },
  {
   "title": "Safe's EURe balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "safe_EURe_balance{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "EURe balance"
    }
   ]
  },
  {
   "title": "Bot's xDAI balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bot_ETH_balance{job=\"eure-rebalancing-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}