name: Stresstest cron

on: 
  schedule:
    - cron: '0 0 * * *'  # Scheduled every night at 12
  workflow_dispatch: {} # Manual triggering
  push:
    branches:
      - 'ci/stresstest'

jobs:
  update_and_push:
    runs-on: self-hosted
    timeout-minutes: 35

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Choose your Python version
          cache: 'pip'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Try anvil
        run: anvil --version

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements-dev.txt

      - name: Run DB script
        run: |
          cd roles_royce/applications/panic_button_app/config/db
          python3 __init__.py

      - name: RUN Tests
        run: |
          RR_ETH_FORK_URL=${{ secrets.NODE_ETH }} RR_GC_FORK_URL=${{ secrets.NODE_XDAI }} RR_RUN_LOCAL_NODE=1 pytest -v --cov tests/applications/panic_button_app/test_stresstest.py
        env:
          RR_RUN_STRESSTEST: True

      - name: Coverage report
        run: coverage report
      
      - name:  Anvil log
        if: ${{ failure() }}
        run: cat /tmp/rr_fork_node_log.txt
      
      - name: Create PR
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: db updates
          title: "[nightly] db updates"
          body: >
            The nightly job detected updates to the db configs
          labels: bot
          branch: db-updates