{
 "title": "spark-anti-liquidation-bot",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Health factor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "health_factor{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "Health factor"
    },
    {
     "expr": "alerting_health_factor{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "Alerting health factor"
    },
    {
     "expr": "health_factor_threshold{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "Threshold"
    }
   ]
  },
  {
   "title": "Last updated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_updated{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health factor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health_factor{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerting health factor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "alerting_health_factor{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health factor threshold",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "health_factor_threshold{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GNO Spark price",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "GNO_price{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "GNO price"
    }
   ]
  },
  {
   "title": "DAI Spark price",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "DAI_price{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "DAI price"
    }
   ]
  },
  {
   "title": "GNO Spark price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "GNO_price{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "GNO price"
    }
   ]
  },
  {
   "title": "DAI Spark price",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DAI_price{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "DAI price"
    }
   ]
  },
  {
   "title": "GNO deposited",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "GNO_balance{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAI borrowed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DAI_borrowed{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bot's ETH balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bot_ETH_balance{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAI balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DAI_balance{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sDAI balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sDAI_balance{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Equivalent DAI from sDAI redemption",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DAI_equivalent{job=\"spark-anti-liquidation-bot\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}